name: storeman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-155.0.dev <4.0.0'

dependencies:
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^8.0.2

flutter:
  uses-material-design: true

ffigen:
  name: DirectoryUtility
  description: Bindings for DirectoryUtility.
  language: objc
  output: 'lib/directory_utility_bindings.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'SizeCalculator'
    module:
      'SizeCalculator': 'swift_module'
  headers:
    entry-points:
      - '/Users/mishkov/Projects/StoremanMacOS/StoremanMacOS/swift_api.h'