name: storeman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  file_picker: ^8.1.7
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  uuid: ^4.5.1
  app_error:
    git: 
      url: https://github.com/mishkov/app_error_packages
      path: app_error/
  path: ^1.9.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^16.0.0

flutter:
  uses-material-design: true

ffigen:
  name: DirectoryUtility
  description: Bindings for DirectoryUtility.
  language: objc
  output: 'lib/directory_utility_bindings.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'SizeCalculator'
    module:
      'SizeCalculator': 'swift_module'
  headers:
    entry-points:
      - '/Users/mishkov/Projects/StoremanMacOS/StoremanMacOS/swift_api.h'